framework:
    notifier:
        chatter_transports:
             slack: '%env(SLACK_DSN)%'
        #    telegram: '%env(TELEGRAM_DSN)%'
        #texter_transports:
        #    twilio: '%env(TWILIO_DSN)%'
        #    nexmo: '%env(NEXMO_DSN)%'
        #email_transports:
        channel_policy:
            # use chat/slack, chat/telegram, sms/twilio or sms/nexmo
            urgent: ['chat/slack','email']
            high: ['chat/slack','email']
            medium: ['email']
            low: ['email']
        admin_recipients:
            - { email: '%env(ALERT_RECEPIENT_EMAIL)%' }
